export async function GET() {
  const inventory = [
    {
      id: 1,
      name: "All-Purpose Cleaner",
      category: "Cleaning Solutions",
      quantity: 45,
      unit: "bottles",
      minStock: 10,
      costPerUnit: 5.99,
      lastUpdated: "2025-01-14",
    },
    {
      id: 2,
      name: "Glass Cleaner",
      category: "Cleaning Solutions",
      quantity: 3,
      unit: "bottles",
      minStock: 8,
      costPerUnit: 4.49,
      lastUpdated: "2025-01-12",
    },
    {
      id: 3,
      name: "Floor Cleaner",
      category: "Cleaning Solutions",
      quantity: 28,
      unit: "bottles",
      minStock: 10,
      costPerUnit: 7.99,
      lastUpdated: "2025-01-13",
    },
    {
      id: 4,
      name: "Disinfectant Spray",
      category: "Cleaning Solutions",
      quantity: 2,
      unit: "bottles",
      minStock: 8,
      costPerUnit: 6.99,
      lastUpdated: "2025-01-10",
    },
    {
      id: 5,
      name: "Microfiber Cloths",
      category: "Tools & Equipment",
      quantity: 120,
      unit: "pcs",
      minStock: 20,
      costPerUnit: 2.99,
      lastUpdated: "2025-01-15",
    },
    {
      id: 6,
      name: "Dusters",
      category: "Tools & Equipment",
      quantity: 35,
      unit: "pcs",
      minStock: 10,
      costPerUnit: 3.49,
      lastUpdated: "2025-01-11",
    },
    {
      id: 7,
      name: "Trash Bags",
      category: "Supplies",
      quantity: 8,
      unit: "boxes",
      minStock: 12,
      costPerUnit: 8.99,
      lastUpdated: "2025-01-09",
    },
    {
      id: 8,
      name: "Gloves",
      category: "Supplies",
      quantity: 50,
      unit: "pairs",
      minStock: 15,
      costPerUnit: 1.99,
      lastUpdated: "2025-01-14",
    },
    {
      id: 9,
      name: "Mop Heads",
      category: "Tools & Equipment",
      quantity: 12,
      unit: "pcs",
      minStock: 5,
      costPerUnit: 9.99,
      lastUpdated: "2025-01-08",
    },
    {
      id: 10,
      name: "Sponges",
      category: "Supplies",
      quantity: 67,
      unit: "pcs",
      minStock: 20,
      costPerUnit: 1.49,
      lastUpdated: "2025-01-15",
    },
  ];

  return Response.json(inventory);
}
