import { NextResponse } from "next/server";

const upcomingBookings = [
  {
    id: "#1057",
    date: "2025-04-26",
    dayLabel: "Sat, Apr 26, 2025",
    time: "9:00 AM - 11:00 AM",
    service: "Regular Clean",
    cleaner: "Maria Santos",
    cleanerRating: 4.9,
    amount: 120,
    address: "123 Elm Street, Surrey",
    status: "Confirmed",
    notes: null,
  },
  {
    id: "#1058",
    date: "2025-04-30",
    dayLabel: "Wed, Apr 30, 2025",
    time: "2:00 PM - 4:00 PM",
    service: "Deep Clean",
    cleaner: "James Wilson",
    cleanerRating: 4.7,
    amount: 180,
    address: "123 Elm Street, Surrey",
    status: "Pending",
    notes: "Focus on kitchen and bathrooms",
  },
];

const pastBookings = [
  {
    id: "#1056",
    date: "2025-04-19",
    dayLabel: "Sat, Apr 19, 2025",
    time: "9:00 AM - 11:00 AM",
    service: "Regular Clean",
    cleaner: "Maria Santos",
    cleanerRating: 4.9,
    amount: 120,
    address: "123 Elm Street, Surrey",
    status: "Completed",
    reviewed: true,
    rating: 5,
  },
  {
    id: "#1049",
    date: "2025-04-12",
    dayLabel: "Sat, Apr 12, 2025",
    time: "10:00 AM - 12:00 PM",
    service: "Move-In Clean",
    cleaner: "Sarah Chen",
    cleanerRating: 4.8,
    amount: 250,
    address: "456 Oak Avenue, Vancouver",
    status: "Completed",
    reviewed: true,
    rating: 4,
  },
  {
    id: "#1042",
    date: "2025-04-05",
    dayLabel: "Sat, Apr 5, 2025",
    time: "9:00 AM - 11:00 AM",
    service: "Regular Clean",
    cleaner: "Maria Santos",
    cleanerRating: 4.9,
    amount: 120,
    address: "123 Elm Street, Surrey",
    status: "Completed",
    reviewed: false,
    rating: null,
  },
  {
    id: "#1035",
    date: "2025-03-29",
    dayLabel: "Sat, Mar 29, 2025",
    time: "1:00 PM - 3:00 PM",
    service: "Deep Clean",
    cleaner: "James Wilson",
    cleanerRating: 4.7,
    amount: 180,
    address: "123 Elm Street, Surrey",
    status: "Completed",
    reviewed: true,
    rating: 5,
  },
  {
    id: "#1028",
    date: "2025-03-22",
    dayLabel: "Sat, Mar 22, 2025",
    time: "9:00 AM - 11:00 AM",
    service: "Regular Clean",
    cleaner: "Sarah Chen",
    cleanerRating: 4.8,
    amount: 120,
    address: "123 Elm Street, Surrey",
    status: "Completed",
    reviewed: false,
    rating: null,
  },
];

export async function GET() {
  return NextResponse.json({
    upcoming: upcomingBookings,
    past: pastBookings,
    summary: {
      totalBookings: 12,
      upcomingCount: upcomingBookings.length,
      pastCount: pastBookings.length,
      totalSpent: 790,
      averageRating: 4.7,
    },
  });
}
