export async function GET() {
  const offers = [
    {
      id: 1,
      code: "WELCOME10",
      type: "percentage",
      value: 10,
      minBooking: 80,
      maxUses: 500,
      usedCount: 342,
      isActive: true,
      expiresAt: "2025-06-30",
    },
    {
      id: 2,
      code: "ECO20",
      type: "percentage",
      value: 20,
      minBooking: 100,
      maxUses: 200,
      usedCount: 178,
      isActive: true,
      expiresAt: "2025-03-31",
    },
    {
      id: 3,
      code: "SPRING25",
      type: "fixed",
      value: 25,
      minBooking: 150,
      maxUses: 300,
      usedCount: 89,
      isActive: true,
      expiresAt: "2025-05-31",
    },
    {
      id: 4,
      code: "REFER15",
      type: "percentage",
      value: 15,
      minBooking: 0,
      maxUses: 1000,
      usedCount: 567,
      isActive: true,
      expiresAt: "2025-12-31",
    },
    {
      id: 5,
      code: "CLEAN50",
      type: "fixed",
      value: 50,
      minBooking: 250,
      maxUses: 100,
      usedCount: 45,
      isActive: false,
      expiresAt: "2025-02-28",
    },
    {
      id: 6,
      code: "VIP30",
      type: "percentage",
      value: 30,
      minBooking: 200,
      maxUses: 50,
      usedCount: 50,
      isActive: false,
      expiresAt: "2024-12-31",
    },
  ];

  return Response.json(offers);
}
