export async function GET() {
  const cleaners = [
    {
      id: 1,
      name: "Maria Santos",
      rating: 4.9,
      totalJobs: 142,
      areas: ["Vancouver", "Burnaby", "Richmond"],
      skills: ["Deep Clean", "Eco Clean", "Move In/Out"],
      status: "active",
      initials: "MS",
      joinDate: "2023-03-15",
    },
    {
      id: 2,
      name: "James Wilson",
      rating: 4.7,
      totalJobs: 98,
      areas: ["Surrey", "Langley", "White Rock"],
      skills: ["Regular Clean", "Deep Clean"],
      status: "active",
      initials: "JW",
      joinDate: "2023-06-20",
    },
    {
      id: 3,
      name: "Sarah Chen",
      rating: 4.8,
      totalJobs: 115,
      areas: ["Vancouver", "North Vancouver", "West Vancouver"],
      skills: ["Eco Clean", "Regular Clean", "Move In/Out"],
      status: "active",
      initials: "SC",
      joinDate: "2023-01-10",
    },
    {
      id: 4,
      name: "Tom Kumar",
      rating: 4.6,
      totalJobs: 67,
      areas: ["Coquitlam", "Port Moody", "New Westminster"],
      skills: ["Regular Clean", "Deep Clean"],
      status: "pending",
      initials: "TK",
      joinDate: "2025-01-05",
    },
    {
      id: 5,
      name: "Lisa Park",
      rating: 4.9,
      totalJobs: 128,
      areas: ["Vancouver", "Burnaby", "Richmond", "Surrey"],
      skills: ["Eco Clean", "Move In/Out", "Deep Clean"],
      status: "active",
      initials: "LP",
      joinDate: "2022-11-22",
    },
    {
      id: 6,
      name: "Omar Hassan",
      rating: 4.5,
      totalJobs: 53,
      areas: ["Surrey", "Delta", "Langley"],
      skills: ["Regular Clean", "Eco Clean"],
      status: "suspended",
      initials: "OH",
      joinDate: "2024-04-18",
    },
  ];

  return Response.json(cleaners);
}
