export async function GET() {
  const bookings = [
    {
      id: 1001,
      customerName: "Amanda Johnson",
      serviceType: "Regular Clean",
      date: "2025-01-15",
      startTime: "09:00",
      endTime: "11:00",
      amount: 120,
      status: "confirmed",
      address: "456 Oak Ave, Vancouver",
    },
    {
      id: 1002,
      customerName: "Michael Chen",
      serviceType: "Deep Clean",
      date: "2025-01-15",
      startTime: "10:00",
      endTime: "13:00",
      amount: 220,
      status: "in_progress",
      address: "789 Pine St, Burnaby",
    },
    {
      id: 1003,
      customerName: "Sarah Williams",
      serviceType: "Move Out Clean",
      date: "2025-01-16",
      startTime: "08:00",
      endTime: "14:00",
      amount: 350,
      status: "pending",
      address: "321 Maple Dr, Surrey",
    },
    {
      id: 1004,
      customerName: "David Brown",
      serviceType: "Eco Clean",
      date: "2025-01-16",
      startTime: "14:00",
      endTime: "16:00",
      amount: 150,
      status: "confirmed",
      address: "654 Cedar Ln, Richmond",
    },
    {
      id: 1005,
      customerName: "Emily Davis",
      serviceType: "Regular Clean",
      date: "2025-01-17",
      startTime: "09:00",
      endTime: "11:00",
      amount: 120,
      status: "completed",
      address: "987 Birch Rd, Vancouver",
    },
    {
      id: 1006,
      customerName: "James Wilson",
      serviceType: "Deep Clean",
      date: "2025-01-17",
      startTime: "13:00",
      endTime: "16:00",
      amount: 220,
      status: "completed",
      address: "147 Elm St, New Westminster",
    },
    {
      id: 1007,
      customerName: "Lisa Park",
      serviceType: "Regular Clean",
      date: "2025-01-18",
      startTime: "08:00",
      endTime: "10:00",
      amount: 100,
      status: "cancelled",
      address: "258 Walnut Ave, Coquitlam",
    },
    {
      id: 1008,
      customerName: "Robert Taylor",
      serviceType: "Move In Clean",
      date: "2025-01-18",
      startTime: "10:00",
      endTime: "15:00",
      amount: 300,
      status: "pending",
      address: "369 Ash Ct, Port Moody",
    },
    {
      id: 1009,
      customerName: "Jennifer Martinez",
      serviceType: "Eco Clean",
      date: "2025-01-19",
      startTime: "09:00",
      endTime: "12:00",
      amount: 180,
      status: "confirmed",
      address: "741 Spruce Way, North Van",
    },
    {
      id: 1010,
      customerName: "Christopher Lee",
      serviceType: "Regular Clean",
      date: "2025-01-19",
      startTime: "14:00",
      endTime: "16:00",
      amount: 110,
      status: "in_progress",
      address: "852 Willow Dr, West Vancouver",
    },
    {
      id: 1011,
      customerName: "Amanda Johnson",
      serviceType: "Deep Clean",
      date: "2025-01-20",
      startTime: "08:00",
      endTime: "12:00",
      amount: 200,
      status: "pending",
      address: "456 Oak Ave, Vancouver",
    },
    {
      id: 1012,
      customerName: "Thomas Anderson",
      serviceType: "Eco Clean",
      date: "2025-01-20",
      startTime: "10:00",
      endTime: "13:00",
      amount: 170,
      status: "confirmed",
      address: "963 Redwood Pl, Langley",
    },
  ];

  return Response.json(bookings);
}
